{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0b9be115",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Running on local URL:  http://127.0.0.1:7861\n",
      "IMPORTANT: You are using gradio version 4.25.0, however version 4.44.1 is available, please upgrade.\n",
      "--------\n",
      "\n",
      "To create a public link, set `share=True` in `launch()`.\n",
      "IMPORTANT: You are using gradio version 4.25.0, however version 4.44.1 is available, please upgrade.\n",
      "--------\n",
      "IMPORTANT: You are using gradio version 4.25.0, however version 4.44.1 is available, please upgrade.\n",
      "--------\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div><iframe src=\"http://127.0.0.1:7861/\" width=\"100%\" height=\"500\" allow=\"autoplay; camera; microphone; clipboard-read; clipboard-write;\" frameborder=\"0\" allowfullscreen></iframe></div>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\type_adapter.py\", line 277, in _init_core_attrs\n",
      "    self._core_schema = _getattr_no_parents(self._type, '__pydantic_core_schema__')\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\type_adapter.py\", line 119, in _getattr_no_parents\n",
      "    raise AttributeError(attribute)\n",
      "AttributeError: __pydantic_core_schema__\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\uvicorn\\protocols\\http\\httptools_impl.py\", line 409, in run_asgi\n",
      "    result = await app(  # type: ignore[func-returns-value]\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\uvicorn\\middleware\\proxy_headers.py\", line 60, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\fastapi\\applications.py\", line 1054, in __call__\n",
      "    await super().__call__(scope, receive, send)\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\starlette\\applications.py\", line 112, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\starlette\\middleware\\errors.py\", line 187, in __call__\n",
      "    raise exc\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\starlette\\middleware\\errors.py\", line 165, in __call__\n",
      "    await self.app(scope, receive, _send)\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\gradio\\route_utils.py\", line 686, in __call__\n",
      "    await self.simple_response(scope, receive, send, request_headers=headers)\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\gradio\\route_utils.py\", line 702, in simple_response\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 62, in __call__\n",
      "    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n",
      "    raise exc\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n",
      "    await app(scope, receive, sender)\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\starlette\\routing.py\", line 714, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\starlette\\routing.py\", line 734, in app\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\starlette\\routing.py\", line 288, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\starlette\\routing.py\", line 76, in app\n",
      "    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n",
      "    raise exc\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n",
      "    await app(scope, receive, sender)\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\starlette\\routing.py\", line 73, in app\n",
      "    response = await f(request)\n",
      "               ^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\fastapi\\routing.py\", line 291, in app\n",
      "    solved_result = await solve_dependencies(\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\fastapi\\dependencies\\utils.py\", line 666, in solve_dependencies\n",
      "    ) = await request_body_to_args(  # body_params checked above\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\fastapi\\dependencies\\utils.py\", line 920, in request_body_to_args\n",
      "    fields_to_extract = get_cached_model_fields(first_field.type_)\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\fastapi\\_compat.py\", line 664, in get_cached_model_fields\n",
      "    return get_model_fields(model)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\fastapi\\_compat.py\", line 291, in get_model_fields\n",
      "    ModelField(field_info=field_info, name=name)\n",
      "  File \"<string>\", line 6, in __init__\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\fastapi\\_compat.py\", line 112, in __post_init__\n",
      "    self._type_adapter: TypeAdapter[Any] = TypeAdapter(\n",
      "                                           ^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\type_adapter.py\", line 264, in __init__\n",
      "    self._init_core_attrs(rebuild_mocks=False)\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\type_adapter.py\", line 142, in wrapped\n",
      "    return func(self, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\type_adapter.py\", line 284, in _init_core_attrs\n",
      "    self._core_schema = _get_schema(self._type, config_wrapper, parent_depth=self._parent_depth)\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\type_adapter.py\", line 102, in _get_schema\n",
      "    schema = gen.generate_schema(type_)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 512, in generate_schema\n",
      "    schema = self._generate_schema_inner(obj)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 768, in _generate_schema_inner\n",
      "    return self._annotated_schema(obj)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 1822, in _annotated_schema\n",
      "    schema = self._apply_annotations(source_type, annotations)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 1890, in _apply_annotations\n",
      "    schema = get_inner_schema(source_type)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\_internal\\_schema_generation_shared.py\", line 83, in __call__\n",
      "    schema = self._handler(source_type)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 1972, in new_handler\n",
      "    schema = metadata_get_schema(source, get_inner_schema)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 1968, in <lambda>\n",
      "    lambda source, handler: handler(source)\n",
      "                            ^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\_internal\\_schema_generation_shared.py\", line 83, in __call__\n",
      "    schema = self._handler(source_type)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 1871, in inner_handler\n",
      "    schema = self._generate_schema_inner(obj)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 789, in _generate_schema_inner\n",
      "    return self.match_type(obj)\n",
      "           ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 871, in match_type\n",
      "    return self._match_generic_type(obj, origin)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 895, in _match_generic_type\n",
      "    return self._union_schema(obj)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 1207, in _union_schema\n",
      "    choices.append(self.generate_schema(arg))\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 512, in generate_schema\n",
      "    schema = self._generate_schema_inner(obj)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 789, in _generate_schema_inner\n",
      "    return self.match_type(obj)\n",
      "           ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 875, in match_type\n",
      "    return self._unknown_type_schema(obj)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 415, in _unknown_type_schema\n",
      "    raise PydanticSchemaGenerationError(\n",
      "pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'starlette.requests.Request'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.\n",
      "\n",
      "If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.\n",
      "\n",
      "For further information visit https://errors.pydantic.dev/2.8/u/schema-for-unknown-type\n",
      "ERROR:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\type_adapter.py\", line 277, in _init_core_attrs\n",
      "    self._core_schema = _getattr_no_parents(self._type, '__pydantic_core_schema__')\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\type_adapter.py\", line 119, in _getattr_no_parents\n",
      "    raise AttributeError(attribute)\n",
      "AttributeError: __pydantic_core_schema__\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\uvicorn\\protocols\\http\\httptools_impl.py\", line 409, in run_asgi\n",
      "    result = await app(  # type: ignore[func-returns-value]\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\uvicorn\\middleware\\proxy_headers.py\", line 60, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\fastapi\\applications.py\", line 1054, in __call__\n",
      "    await super().__call__(scope, receive, send)\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\starlette\\applications.py\", line 112, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\starlette\\middleware\\errors.py\", line 187, in __call__\n",
      "    raise exc\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\starlette\\middleware\\errors.py\", line 165, in __call__\n",
      "    await self.app(scope, receive, _send)\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\gradio\\route_utils.py\", line 686, in __call__\n",
      "    await self.simple_response(scope, receive, send, request_headers=headers)\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\gradio\\route_utils.py\", line 702, in simple_response\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 62, in __call__\n",
      "    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n",
      "    raise exc\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n",
      "    await app(scope, receive, sender)\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\starlette\\routing.py\", line 714, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\starlette\\routing.py\", line 734, in app\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\starlette\\routing.py\", line 288, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\starlette\\routing.py\", line 76, in app\n",
      "    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n",
      "    raise exc\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n",
      "    await app(scope, receive, sender)\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\starlette\\routing.py\", line 73, in app\n",
      "    response = await f(request)\n",
      "               ^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\fastapi\\routing.py\", line 291, in app\n",
      "    solved_result = await solve_dependencies(\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\fastapi\\dependencies\\utils.py\", line 666, in solve_dependencies\n",
      "    ) = await request_body_to_args(  # body_params checked above\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\fastapi\\dependencies\\utils.py\", line 920, in request_body_to_args\n",
      "    fields_to_extract = get_cached_model_fields(first_field.type_)\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\fastapi\\_compat.py\", line 664, in get_cached_model_fields\n",
      "    return get_model_fields(model)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\fastapi\\_compat.py\", line 291, in get_model_fields\n",
      "    ModelField(field_info=field_info, name=name)\n",
      "  File \"<string>\", line 6, in __init__\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\fastapi\\_compat.py\", line 112, in __post_init__\n",
      "    self._type_adapter: TypeAdapter[Any] = TypeAdapter(\n",
      "                                           ^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\type_adapter.py\", line 264, in __init__\n",
      "    self._init_core_attrs(rebuild_mocks=False)\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\type_adapter.py\", line 142, in wrapped\n",
      "    return func(self, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\type_adapter.py\", line 284, in _init_core_attrs\n",
      "    self._core_schema = _get_schema(self._type, config_wrapper, parent_depth=self._parent_depth)\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\type_adapter.py\", line 102, in _get_schema\n",
      "    schema = gen.generate_schema(type_)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 512, in generate_schema\n",
      "    schema = self._generate_schema_inner(obj)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 768, in _generate_schema_inner\n",
      "    return self._annotated_schema(obj)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 1822, in _annotated_schema\n",
      "    schema = self._apply_annotations(source_type, annotations)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 1890, in _apply_annotations\n",
      "    schema = get_inner_schema(source_type)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\_internal\\_schema_generation_shared.py\", line 83, in __call__\n",
      "    schema = self._handler(source_type)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 1972, in new_handler\n",
      "    schema = metadata_get_schema(source, get_inner_schema)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 1968, in <lambda>\n",
      "    lambda source, handler: handler(source)\n",
      "                            ^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\_internal\\_schema_generation_shared.py\", line 83, in __call__\n",
      "    schema = self._handler(source_type)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 1871, in inner_handler\n",
      "    schema = self._generate_schema_inner(obj)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 789, in _generate_schema_inner\n",
      "    return self.match_type(obj)\n",
      "           ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 871, in match_type\n",
      "    return self._match_generic_type(obj, origin)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 895, in _match_generic_type\n",
      "    return self._union_schema(obj)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 1207, in _union_schema\n",
      "    choices.append(self.generate_schema(arg))\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 512, in generate_schema\n",
      "    schema = self._generate_schema_inner(obj)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 789, in _generate_schema_inner\n",
      "    return self.match_type(obj)\n",
      "           ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 875, in match_type\n",
      "    return self._unknown_type_schema(obj)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 415, in _unknown_type_schema\n",
      "    raise PydanticSchemaGenerationError(\n",
      "pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'starlette.requests.Request'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.\n",
      "\n",
      "If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.\n",
      "\n",
      "For further information visit https://errors.pydantic.dev/2.8/u/schema-for-unknown-type\n",
      "ERROR:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\type_adapter.py\", line 277, in _init_core_attrs\n",
      "    self._core_schema = _getattr_no_parents(self._type, '__pydantic_core_schema__')\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\type_adapter.py\", line 119, in _getattr_no_parents\n",
      "    raise AttributeError(attribute)\n",
      "AttributeError: __pydantic_core_schema__\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\uvicorn\\protocols\\http\\httptools_impl.py\", line 409, in run_asgi\n",
      "    result = await app(  # type: ignore[func-returns-value]\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\uvicorn\\middleware\\proxy_headers.py\", line 60, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\fastapi\\applications.py\", line 1054, in __call__\n",
      "    await super().__call__(scope, receive, send)\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\starlette\\applications.py\", line 112, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\starlette\\middleware\\errors.py\", line 187, in __call__\n",
      "    raise exc\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\starlette\\middleware\\errors.py\", line 165, in __call__\n",
      "    await self.app(scope, receive, _send)\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\gradio\\route_utils.py\", line 686, in __call__\n",
      "    await self.simple_response(scope, receive, send, request_headers=headers)\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\gradio\\route_utils.py\", line 702, in simple_response\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 62, in __call__\n",
      "    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n",
      "    raise exc\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n",
      "    await app(scope, receive, sender)\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\starlette\\routing.py\", line 714, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\starlette\\routing.py\", line 734, in app\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\starlette\\routing.py\", line 288, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\starlette\\routing.py\", line 76, in app\n",
      "    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n",
      "    raise exc\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n",
      "    await app(scope, receive, sender)\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\starlette\\routing.py\", line 73, in app\n",
      "    response = await f(request)\n",
      "               ^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\fastapi\\routing.py\", line 291, in app\n",
      "    solved_result = await solve_dependencies(\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\fastapi\\dependencies\\utils.py\", line 666, in solve_dependencies\n",
      "    ) = await request_body_to_args(  # body_params checked above\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\fastapi\\dependencies\\utils.py\", line 920, in request_body_to_args\n",
      "    fields_to_extract = get_cached_model_fields(first_field.type_)\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\fastapi\\_compat.py\", line 664, in get_cached_model_fields\n",
      "    return get_model_fields(model)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\fastapi\\_compat.py\", line 291, in get_model_fields\n",
      "    ModelField(field_info=field_info, name=name)\n",
      "  File \"<string>\", line 6, in __init__\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\fastapi\\_compat.py\", line 112, in __post_init__\n",
      "    self._type_adapter: TypeAdapter[Any] = TypeAdapter(\n",
      "                                           ^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\type_adapter.py\", line 264, in __init__\n",
      "    self._init_core_attrs(rebuild_mocks=False)\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\type_adapter.py\", line 142, in wrapped\n",
      "    return func(self, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\type_adapter.py\", line 284, in _init_core_attrs\n",
      "    self._core_schema = _get_schema(self._type, config_wrapper, parent_depth=self._parent_depth)\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\type_adapter.py\", line 102, in _get_schema\n",
      "    schema = gen.generate_schema(type_)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 512, in generate_schema\n",
      "    schema = self._generate_schema_inner(obj)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 768, in _generate_schema_inner\n",
      "    return self._annotated_schema(obj)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 1822, in _annotated_schema\n",
      "    schema = self._apply_annotations(source_type, annotations)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 1890, in _apply_annotations\n",
      "    schema = get_inner_schema(source_type)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\_internal\\_schema_generation_shared.py\", line 83, in __call__\n",
      "    schema = self._handler(source_type)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 1972, in new_handler\n",
      "    schema = metadata_get_schema(source, get_inner_schema)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 1968, in <lambda>\n",
      "    lambda source, handler: handler(source)\n",
      "                            ^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\_internal\\_schema_generation_shared.py\", line 83, in __call__\n",
      "    schema = self._handler(source_type)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 1871, in inner_handler\n",
      "    schema = self._generate_schema_inner(obj)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 789, in _generate_schema_inner\n",
      "    return self.match_type(obj)\n",
      "           ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 871, in match_type\n",
      "    return self._match_generic_type(obj, origin)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 895, in _match_generic_type\n",
      "    return self._union_schema(obj)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 1207, in _union_schema\n",
      "    choices.append(self.generate_schema(arg))\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 512, in generate_schema\n",
      "    schema = self._generate_schema_inner(obj)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 789, in _generate_schema_inner\n",
      "    return self.match_type(obj)\n",
      "           ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 875, in match_type\n",
      "    return self._unknown_type_schema(obj)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\hermanhk\\anaconda3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 415, in _unknown_type_schema\n",
      "    raise PydanticSchemaGenerationError(\n",
      "pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'starlette.requests.Request'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.\n",
      "\n",
      "If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.\n",
      "\n",
      "For further information visit https://errors.pydantic.dev/2.8/u/schema-for-unknown-type\n"
     ]
    }
   ],
   "source": [
    "import gradio as gr\n",
    "import pandas as pd\n",
    "import seaborn as sns\n",
    "import matplotlib.pyplot as plt\n",
    "import numpy as np\n",
    "from tensorflow.keras.models import load_model\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "import os\n",
    "\n",
    "# === Charger modèle et données en toute sécurité ===\n",
    "try:\n",
    "    model = load_model('D:/RATRAPAGE/heart_model.h5')\n",
    "except Exception as e:\n",
    "    raise FileNotFoundError(f\"Erreur lors du chargement du modèle : {e}\")\n",
    "\n",
    "try:\n",
    "    df = pd.read_excel('D:/cours IFI/Fouille_Donees/dataset/archive1/heart_excel.xlsx')\n",
    "except Exception as e:\n",
    "    raise FileNotFoundError(f\"Erreur lors du chargement des données : {e}\")\n",
    "\n",
    "# === Encodage des variables catégorielles ===\n",
    "df_encoded = pd.get_dummies(df.drop(\"HeartDisease\", axis=1), drop_first=True)\n",
    "\n",
    "# === Initialisation du scaler ===\n",
    "scaler = StandardScaler()\n",
    "scaler.fit(df_encoded)\n",
    "\n",
    "# === Fonctions d'analyse exploratoire ===\n",
    "def eda_plot():\n",
    "    fig, ax = plt.subplots(figsize=(10, 6))\n",
    "    sns.heatmap(df.corr(numeric_only=True), annot=True, cmap=\"coolwarm\", fmt=\".2f\", ax=ax)\n",
    "    plt.title(\"Matrice de corrélation\")\n",
    "    return fig\n",
    "\n",
    "def summary():\n",
    "    return df.describe().T\n",
    "\n",
    "# === Fonction de prédiction ===\n",
    "def predict_disease(age, sex, resting_bp, cholesterol, fasting_bs, max_hr, oldpeak,\n",
    "                    cpt_ata, cpt_nap, cpt_ta, ecg_normal, ecg_st,\n",
    "                    exercise_angina_y, st_flat, st_up):\n",
    "    \n",
    "    input_data = pd.DataFrame([{\n",
    "        \"Age\": age,\n",
    "        \"Sex\": sex,\n",
    "        \"RestingBP\": resting_bp,\n",
    "        \"Cholesterol\": cholesterol,\n",
    "        \"FastingBS\": fasting_bs,\n",
    "        \"MaxHR\": max_hr,\n",
    "        \"Oldpeak\": oldpeak,\n",
    "        \"ChestPainType_ATA\": int(cpt_ata),\n",
    "        \"ChestPainType_NAP\": int(cpt_nap),\n",
    "        \"ChestPainType_TA\": int(cpt_ta),\n",
    "        \"RestingECG_Normal\": int(ecg_normal),\n",
    "        \"RestingECG_ST\": int(ecg_st),\n",
    "        \"ExerciseAngina_Y\": int(exercise_angina_y),\n",
    "        \"ST_Slope_Flat\": int(st_flat),\n",
    "        \"ST_Slope_Up\": int(st_up)\n",
    "    }])\n",
    "\n",
    "    try:\n",
    "        scaled_input = scaler.transform(input_data)\n",
    "        prediction = model.predict(scaled_input)[0][0]\n",
    "        pred_label = \"🩺 Risque de maladie cardiaque\" if prediction > 0.5 else \"✅ Pas de risque détecté\"\n",
    "        return f\"{pred_label} (Probabilité : {prediction:.2f})\"\n",
    "    except Exception as e:\n",
    "        return f\"Erreur de prédiction : {str(e)}\"\n",
    "\n",
    "# === Interface Gradio ===\n",
    "\n",
    "# Onglet EDA\n",
    "with gr.Blocks() as eda_tab:\n",
    "    gr.Markdown(\"## 🔍 Analyse Exploratoire\")\n",
    "    with gr.Row():\n",
    "        summary_output = gr.Dataframe()\n",
    "        correlation_output = gr.Plot()\n",
    "\n",
    "    btn_summary = gr.Button(\"📊 Afficher Résumé\")\n",
    "    btn_corr = gr.Button(\"🔗 Afficher Matrice de corrélation\")\n",
    "\n",
    "    btn_summary.click(fn=summary, outputs=summary_output)\n",
    "    btn_corr.click(fn=eda_plot, outputs=correlation_output)\n",
    "\n",
    "# Onglet Prédiction\n",
    "with gr.Blocks() as predict_tab:\n",
    "    gr.Markdown(\"## 🧠 Prédiction de Maladie Cardiaque\")\n",
    "    with gr.Row():\n",
    "        age = gr.Number(label=\"Âge\")\n",
    "        sex = gr.Radio(choices=[0, 1], label=\"Sexe (0=F, 1=M)\")\n",
    "\n",
    "    with gr.Row():\n",
    "        resting_bp = gr.Number(label=\"Pression Artérielle au Repos\")\n",
    "        cholesterol = gr.Number(label=\"Cholestérol\")\n",
    "\n",
    "    with gr.Row():\n",
    "        fasting_bs = gr.Radio(choices=[0, 1], label=\"Glycémie à jeun (>120 mg/dl)\")\n",
    "        max_hr = gr.Number(label=\"Fréquence Cardiaque Max\")\n",
    "\n",
    "    oldpeak = gr.Number(label=\"Oldpeak (dépression ST)\")\n",
    "\n",
    "    gr.Markdown(\"### 🫀 Type de Douleur Thoracique\")\n",
    "    cpt_ata = gr.Checkbox(label=\"Angine typique (ATA)\")\n",
    "    cpt_nap = gr.Checkbox(label=\"Douleur non angineuse (NAP)\")\n",
    "    cpt_ta = gr.Checkbox(label=\"Angine atypique (TA)\")\n",
    "\n",
    "    gr.Markdown(\"### 📉 Résultat ECG\")\n",
    "    ecg_normal = gr.Checkbox(label=\"Normal\")\n",
    "    ecg_st = gr.Checkbox(label=\"Anomalie ST\")\n",
    "\n",
    "    gr.Markdown(\"### 🏃‍♂️ Angine à l'Effort\")\n",
    "    exercise_angina_y = gr.Checkbox(label=\"Angine induite par exercice\")\n",
    "\n",
    "    gr.Markdown(\"### 📈 Pente du Segment ST\")\n",
    "    st_flat = gr.Checkbox(label=\"Plate\")\n",
    "    st_up = gr.Checkbox(label=\"Montante\")\n",
    "\n",
    "    prediction_output = gr.Textbox(label=\"Résultat\")\n",
    "\n",
    "    btn_predict = gr.Button(\"🔮 Prédire\")\n",
    "    btn_predict.click(\n",
    "        fn=predict_disease,\n",
    "        inputs=[age, sex, resting_bp, cholesterol, fasting_bs, max_hr, oldpeak,\n",
    "                cpt_ata, cpt_nap, cpt_ta, ecg_normal, ecg_st,\n",
    "                exercise_angina_y, st_flat, st_up],\n",
    "        outputs=prediction_output\n",
    "    )\n",
    "\n",
    "# Application multi-onglet avec configuration robuste\n",
    "demo = gr.TabbedInterface(\n",
    "    interface_list=[eda_tab, predict_tab],\n",
    "    title=\"🧬 Application d'Analyse Cardiaque\"\n",
    ")\n",
    "\n",
    "# === Lancement protégé ===\n",
    "demo.launch(\n",
    "    server_port=7861,  # changer si nécessaire\n",
    "    inbrowser=True,\n",
    "    debug=True          # pour voir les erreurs détaillées\n",
    ")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
